code --install-extension 2gua.rainbow-brackets
code --install-extension amirmarmul.laravel-blade-vscode
code --install-extension bierner.lit-html
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension davidbabel.vscode-simpler-icons
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension formulahendry.code-runner
code --install-extension getpsalm.psalm-vscode-plugin
code --install-extension HookyQR.beautify
code --install-extension hoovercj.vscode-power-mode
code --install-extension IronGeek.vscode-env
code --install-extension jaycetyle.vscode-gnu-global
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension kokororin.vscode-phpfmt
code --install-extension ms-azuretools.vscode-docker
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension pawelgrzybek.gatito-theme
code --install-extension PKief.material-icon-theme
code --install-extension rafamel.subtle-brackets
code --install-extension shevaua.phpcs
code --install-extension syler.sass-indented
code --install-extension sysoev.language-stylus
code --install-extension vscodevim.vim
code --install-extension whatwedo.twig
